var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var esttext = new Schema({
    LANDINGTITLE1: {type: String, default: "Meie tehtud"},
    LANDINGMESSAGE: {type: String, default: "elektrilahendused"},
    LANDINGTITLE2: {type: String, default: "on kõrgusi ületavad"},
    LANDINGBUTTON1: {type: String, default: "SAADA PÄRING"},
    LANDINGBUTTON2: {type: String, default: "ETTEVÕTTEST"},
    SIDEMENUINTRO: {type: String, default: "Tutvustus"},
    INTROTEXT: {type: String, default: "Oleme tugev Eesti ettevõte, kes võtnud oma missiooniks lahendada kõik elektritöödega seotud ülesanded"},
    INTROSUBHEADING1: {type: String, default: "Elektritööd"},
    INTROSUBHEADING2: {type: String, default: "Elektriklipide ehitus"},
    INTROSUBHEADING3: {type: String, default: "Seadmete paigaldus"},
    INTROSUBHEADING4: {type: String, default: "Projekteerimine"},
    INTROSUBTEXT1: {type: String, default: "See on meie peamine tööpõld"},
    INTROSUBTEXT2: {type: String, default: "Omame pikaajalist kogemust elektrikilpide ehitusel ja remontimisel"},
    INTROSUBTEXT3: {type: String, default: "Meil on oskuslik tööjõud erinevate elektriseadmete installeerimiseks"},
    INTROSUBTEXT4: {type: String, default: "Oleme koostanud elektriprojekte juba ligi 25 aastat"},
    SIDEMENUCREW: {type: String, default: "Meeskond"},
    CREWTEXT: {type: String, default: "Ettevõtte võtmetegijad annavad asjalikku ja profesionaalset nõu ning meie tehtud tööd räägivad enda eest"},
    CREWPOS1: {type: String, default: "Juhataja"},
    CREWNAME1: {type: String, default: "Priit Laur"},
    CREWMAIL1: {type: String, default: "priit.laur@elektrosystem.ee"},
    CREWPOS2: {type: String, default: "Projektijuhataja"},
    CREWNAME2: {type: String, default: "Marco Kruustük"},
    CREWMAIL2: {type: String, default: "marco.kruustuk@elektrosystem.ee"},
    CREWPOS3: {type: String, default: "Projektijuhataja"},
    CREWNAME3: {type: String, default: "Sander Seene"},
    CREWMAIL3: {type: String, default: "sander.seene@elektrosystem.ee"},
    MAPEXTRA: {type: String, default: "Avage google mapsis"},
    MAIL: {type: String, default: "E-mail: info@elektrosystem.ee"},
    ADDRESS: {type: String, default: "Aadress: Tähe 127c, Tartu"},
    PHONE: {type: String, default: "Telefon: +372 7366019"},
    CONTACTHEAD1: {type: String, default: "Soovite infot?"},
    CONTACTHEAD2: {type: String, default: "Võtke meiega ühendust"},
    FORMNAME: {type: String, default: "Nimi"},
    FORMEMAIL: {type: String, default: "E-mail aadress"},
    FORMMESSAGE: {type: String, default: "Sõnum"}
});
module.exports = mongoose.model('esttext', esttext);